### ISSUE TITLE
Doesn't work with non-Boost ASIO

### ISSUE THREAD

**Issue by nlguillemot** [RobertLeahy/ASIO-cURL#1]
Two problems:
1. Depends on Boost
2. Depends specifically on Boost.ASIO

It would be nice if this library could be used without having to include all of Boost. Also, it would be nice if it was possible to use the version of ASIO that isn't part of Boost.

**Comment by RobertLeahy** [comment]
See: db1dc14b7fd91d5963b3462dca7778174f089350.

Also: [Continuous integration builds](https://travis-ci.org/RobertLeahy/ASIO-cURL/builds/155253793).  [#36.7](https://travis-ci.org/RobertLeahy/ASIO-cURL/jobs/155253800), [#36.9](https://travis-ci.org/RobertLeahy/ASIO-cURL/jobs/155253802), & [#36.11](https://travis-ci.org/RobertLeahy/ASIO-cURL/jobs/155253804) don't even have Boost installed as they have `USE_BOOST_FUTURE=0` and `USE_BOOST_ASIO=0`.
